In [4]:
from sklearn.linear_model import LinearRegression, LogisticRegressionCV
from aeon.datasets import  load_from_tsfile
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from aeon.transformations.collection.convolution_based import MiniRocketMultivariate
from aeon.datasets import load_basic_motions


In [7]:
!python -v

import _frozen_importlib # frozen
import _imp # builtin
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import '_warnings' # <class '_frozen_importlib.BuiltinImporter'>
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import '_io' # <class '_frozen_importlib.BuiltinImporter'>
import 'marshal' # <class '_frozen_importlib.BuiltinImporter'>
import 'posix' # <class '_frozen_importlib.BuiltinImporter'>
import '_frozen_importlib_external' # <class '_frozen_importlib.FrozenImporter'>
# installing zipimport hook
import 'time' # <class '_frozen_importlib.BuiltinImporter'>
import 'zipimport' # <class '_frozen_importlib.FrozenImporter'>
# installed zipimport hook
# /home/davide/miniconda3/envs/TSCaptum311/lib/python3.11/encodings/__pycache__/__init__.cpython-311.pyc matches /home/davide/miniconda3/envs/TSCaptum311/lib/python3.11/encodings/__init__.py
# code object from '/home/davide/miniconda3/envs/TSCaptum311/lib/python3.11/encodings/__pycache__/__init__.cpython-311

In [8]:
from tsCaptum.ts_captum_method import Feature_Ablation, Feature_Permutation

# load regression data


In [9]:
X_train_reg, y_train_reg = load_from_tsfile("./data/AppliancesEnergy_TRAIN.ts")
X_test_reg, y_test_reg = load_from_tsfile("./data/AppliancesEnergy_TEST.ts")

# train regression model

In [10]:
clf =  make_pipeline( MiniRocketMultivariate(n_jobs=-1), StandardScaler(),
                      LinearRegression( n_jobs = -1))
clf.fit(X_train_reg,y_train_reg)
clf.score(X_test_reg, y_test_reg)

0.5420600269731599

# test regression methods .. TBC

In [11]:
myfa = Feature_Ablation(clf)
exp = myfa.explain(  X_test_reg[:2] )
print( type(exp), exp.shape, exp[:,:5,:5]  , "\n\n")

myfp = Feature_Permutation(clf)
exp = myfp.explain( X_test_reg[:2])
print( type(exp), exp.shape, exp[:,:5,:5]  , "\n\n")


tmp = Feature_Permutation(clf=clf)
tmp3 = Feature_Permutation(clf=clf, clf_type="regressor")

<class 'numpy.ndarray'> (2, 24, 144) [[[-0.02573681 -0.00404549 -0.01771736 -0.00264645  0.00416088]
  [-0.01262856 -0.01827145 -0.12257767 -0.01614571 -0.15222454]
  [ 0.04004097  0.03127766 -0.00219917 -0.00697041 -0.00518322]
  [ 0.06549549  0.00125217 -0.06796932 -0.06739712 -0.16692352]
  [-0.14769077 -0.19347286 -0.2391653  -0.24162197 -0.32153416]]

 [[ 0.00492859  0.01392937  0.02258682  0.02529907  0.05384445]
  [ 0.02045441  0.02164078 -0.02195168  0.14097786  0.02272415]
  [ 0.05850029  0.07066727  0.04148102  0.02645874  0.01840401]
  [ 0.04247284 -0.00858498 -0.03930664  0.01515198 -0.10315132]
  [-0.17253494 -0.20374298 -0.23417854 -0.24288368 -0.32317924]]] 


<class 'numpy.ndarray'> (2, 24, 144) [[[-8.11576843e-03 -1.74894333e-02 -2.47440338e-02 -2.47907639e-02
   -4.22286987e-03]
  [-3.25803757e-02 -3.64723206e-02 -8.21475983e-02 -4.59156036e-02
   -5.03664017e-02]
  [-4.76837158e-06 -4.30202484e-03 -4.77123260e-03 -2.40707397e-03
   -2.75230408e-03]
  [-5.35345078e-02

# load classification data



In [12]:
X_train_clf, y_train_clf = load_basic_motions(split="train")
X_test_clf, y_test_clf = load_basic_motions(split="test")


# train classification model

In [13]:
clf =  make_pipeline( MiniRocketMultivariate(n_jobs=-1), StandardScaler(),
                      LogisticRegressionCV(cv = 5, random_state=0, n_jobs = -1,max_iter=1000))
clf.fit( X_train_clf, y_train_clf)
clf.score ( X_test_clf, y_test_clf )

1.0

# test XAI classification methods TBC

In [14]:
myfp4clf = Feature_Permutation(clf=clf, clf_type="classifier")
exp = myfp4clf.explain( X_test_clf[:2], labels=y_test_clf[:2] )
print( type(exp), exp.shape,exp[:,:5,:5]  , "\n\n")

myfp4clf2 = Feature_Permutation(clf=clf)
exp = myfp4clf2.explain( X_test_clf[:2], labels=y_test_clf[:2] )
print( type(exp), exp.shape, exp[:,:5,:5]  , "\n\n")

myfa4clf = Feature_Ablation(clf=clf, clf_type="classifier")
exp = myfa4clf.explain( X_test_clf[:2], labels=y_test_clf[:2] )
print( type(exp), exp.shape, exp[:,:5,:5]   , "\n\n")

<class 'numpy.ndarray'> (2, 6, 100) [[[ 2.09981049e-05  1.95596432e-05 -4.12707705e-05  2.49961687e-05
   -8.08386660e-06]
  [-1.26687528e-05 -3.74253755e-05  4.05554369e-04  2.31518671e-04
    4.66499552e-04]
  [-2.48587637e-05 -1.94392733e-05  8.27762731e-04  3.36486837e-04
    9.89174621e-05]
  [ 1.31882828e-05  1.77453078e-05  9.87143985e-04  1.20632709e-04
    3.36433531e-04]
  [ 5.18994642e-06 -1.05858758e-05 -6.69838469e-05  1.11306374e-04
    2.33994084e-04]]

 [[-8.27251942e-05 -8.02925685e-05 -9.55454742e-04 -4.55659073e-04
    2.46951388e-05]
  [ 2.94982843e-05  2.21469228e-05 -1.08818937e-03 -9.87545324e-04
   -7.83393121e-04]
  [ 5.72036566e-05  5.90542570e-05 -1.44212948e-03 -9.99847143e-04
   -1.14147055e-04]
  [-9.40633848e-05 -1.09382384e-04 -1.64709518e-03 -9.00218347e-04
   -5.52288579e-04]
  [ 6.34214870e-07  4.68162123e-06 -7.93195686e-04 -4.01851319e-04
   -2.92200403e-04]]] 


<class 'numpy.ndarray'> (2, 6, 100) [[[ 2.09981049e-05  1.95596432e-05 -4.12707705e-05 

# TODO: 
 

 check with univariate datasets
 
check other python version requirements are torch, captum and sklearn

# sktime classification

In [15]:
from sktime.classification.dictionary_based import MUSE
clf = MUSE(window_inc=4, use_first_order_differences=False,support_probabilities=True,n_jobs=-1)
clf.fit(X_train_clf, y_train_clf)
print ("MUSE accuracy is",clf.score(X_test_clf,y_test_clf))

/home/davide/miniconda3/envs/TSCaptum311/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1216: UserWarning: 'n_jobs' > 1 does not have any effect when 'solver' is set to 'liblinear'. Got 'n_jobs' = 20.
  warnings.warn(


MUSE accuracy is 1.0


In [16]:
myfp4clf = Feature_Permutation(clf=clf, clf_type="classifier")
exp = myfp4clf.explain( X_test_clf[:2], labels=y_test_clf[:2] )
print( type(exp), exp.shape,exp[:,:5,:5]  , "\n\n")

myfp4clf2 = Feature_Permutation(clf=clf)
exp = myfp4clf2.explain( X_test_clf[:2], labels=y_test_clf[:2] )
print( type(exp), exp.shape, exp[:,:5,:5]  , "\n\n")

myfa4clf = Feature_Ablation(clf=clf, clf_type="classifier")
exp = myfa4clf.explain( X_test_clf[:2], labels=y_test_clf[:2] )
print( type(exp), exp.shape, exp[:,:5,:5]   , "\n\n")

<class 'numpy.ndarray'> (2, 6, 100) [[[-5.93921783e-05  1.23461090e-03  5.92756561e-03  4.27730146e-03
    1.68119932e-03]
  [-2.12498614e-04  2.24971120e-03 -8.82070121e-04 -2.60255358e-03
   -3.25963774e-04]
  [-4.04694121e-05  6.80328105e-05  2.01315820e-03  4.12650241e-04
    6.85613598e-04]
  [ 0.00000000e+00  0.00000000e+00 -1.34126334e-05 -6.16500163e-04
   -1.50942010e-04]
  [ 0.00000000e+00  0.00000000e+00 -2.57221041e-03 -3.06469785e-04
    9.23894471e-04]]

 [[-2.40384879e-06 -1.94638021e-05 -1.32786024e-05  4.83975378e-05
   -5.27607904e-06]
  [-1.41106324e-05 -4.25134432e-05 -1.21414012e-04 -1.85975023e-04
   -2.56207553e-04]
  [ 1.78692213e-06  5.00302422e-06  6.65449822e-06  6.20405897e-06
   -6.07401594e-06]
  [ 4.27176442e-06  2.29798105e-06 -3.20486929e-06 -1.27940223e-05
    2.94584658e-06]
  [ 2.10646316e-06 -1.21007859e-07  9.86817453e-06  6.16465864e-06
   -3.35967694e-05]]] 


<class 'numpy.ndarray'> (2, 6, 100) [[[-5.93921783e-05  1.23461090e-03  5.92756561e-03 

# sktime regression

In [17]:
from sktime.regression.kernel_based import RocketRegressor

regressor = RocketRegressor(num_kernels=500,n_jobs=-1) 
regressor.fit(X_train_reg, y_train_reg)
print( " KNeighborsTimeSeriesRegressor ",regressor.score(X_test_reg, y_test_reg) )

 KNeighborsTimeSeriesRegressor  0.5531852142376538


In [ ]:
myfp4clf = Feature_Permutation(clf=regressor, clf_type="regressor")
exp = myfp4clf.explain( X_test_reg[:2])
print( type(exp), exp.shape,exp[:,:5,:5]  , "\n\n")

myfp4clf2 = Feature_Permutation(clf=regressor)
exp = myfp4clf2.explain( X_test_reg[:2] )
print( type(exp), exp.shape, exp[:,:5,:5]  , "\n\n")

myfa4clf = Feature_Ablation(clf=regressor, clf_type="regressor")
exp = myfa4clf.explain( X_test_reg[:2] )
print( type(exp), exp.shape, exp[:,:5,:5]   , "\n\n")